name: ncov-ingest
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_4
  - pip=20.0.2=py37_1
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=45.2.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - boto3==1.11.15
    - botocore==1.14.15
    - docutils==0.15.2
    - fsspec==0.6.2
    - jmespath==0.9.4
    - numpy==1.18.1
    - pandas==1.0.1
    - python-dateutil==2.8.1
    - pytz==2019.3
    - s3fs==0.4.0
    - s3transfer==0.3.3
    - six==1.14.0
    - urllib3==1.25.8
prefix: /home/kairsten/miniconda3/envs/ncov-ingest

