
idcolumn:
    gisaid:  gisaid_epi_isl
    genbank: genbank_accession


slack_channel: 
    genbank: ncov-genbank-updates
    gisaid: ncov-gisaid-updates

fetch: "no"

gisaid_endpoint: NA
gisaid_login: NA

slack_token : NA