database_name: "genbank"

fetch_from_database: false
trigger_rebuild: false
trigger_counts: false

s3_src: "s3://nextstrain-data/files/ncov/open"
s3_dst: "s3://nextstrain-data/files/ncov/open"

keep_all_files: False
