name: Ingest 2019-nCov/SARS-CoV-2 data from GISAID for nextstrain.org/ncov

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - source-data/gisaid_annotations.tsv

  schedule:
    # See table of scheduled times in the README.  Times here are UTC.
    - cron: '0 6,12,15,21 * * *'

  # Manually triggered using `./bin/trigger ingest`
  repository_dispatch:
    types: ingest

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install pipenv
        pipenv sync
        pipenv run ./bin/ingest-gisaid
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
