name: GISAID full Nextclade run

on:
  # Manually triggered using:
  #  - ./bin/trigger gisaid/nextclade-full-run`   (only GISAID)
  #  - ./bin/trigger nextclade-full-run           (GISAID and GenBank)
  repository_dispatch:
    types:
      - gisaid/nextclade-full-run
      - nextclade-full-run

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  GISAID-Full-Nextclade-Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nextstrain/.github/actions/setup-nextstrain-cli@master

      - name: "./bin/run-nextclade-full-aws --database=gisaid"
        run: |
          ./bin/run-nextclade-full-aws --database=gisaid

        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ncov-gisaid-updates
